### ISSUE TITLE
Convert Slack link to invite

### ISSUE THREAD

**Issue by Maktm** [Ethiopia-COVID19/community#2]
The link to the Slack workspace is for signing in, not signing up so change it to an invite so people can register for the workspace.

**Comment by vuvas** [comment]
> The link to the Slack workspace is for signing in, not signing up so change it to an invite so people can register for the workspace.

Yeah, I have the same issue.

**Comment by nabiloo19** [comment]
Same here

**Comment by dotmike** [comment]
Updated the invite link. Thanks all. Closing
